#!/bin/bash

# Copyright (c) 2012-2013 Los Alamos National Security, LLC, and others.

# This script downloads all the components necessary to run manual-install.

# WARNING: googlecode.com does not work with wget -N for some reason,
# returning 404. That's why some URLs below avoid wget_. It's an old bug that
# Google is ignoring: <http://code.google.com/p/support/issues/detail?id=660>.
# The workaround is to use --continue, but this considerably more error prone.

set -e
set -x

mkdir -p src
cd src

# C source files
wget --continue http://git-core.googlecode.com/files/git-1.8.4.tar.gz
wget -N http://www.python.org/ftp/python/2.7.5/Python-2.7.5.tar.bz2
wget -N http://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.6.tar.gz
wget -N http://pypi.python.org/packages/source/p/pip/pip-1.4.1.tar.gz
wget -N http://prdownloads.sourceforge.net/swig/swig-2.0.11.tar.gz
wget -N http://download.osgeo.org/geos/geos-3.4.2.tar.bz2
wget -N http://download.osgeo.org/gdal/1.10.1/gdal-1.10.1.tar.gz
wget -N http://download.osgeo.org/proj/proj-4.8.0.tar.gz

# pips
wget -N http://pypi.python.org/packages/source/a/anyjson/anyjson-0.3.3.tar.gz
wget -N http://pypi.python.org/packages/source/d/daemon/daemon-1.0.tar.gz
wget -N http://pypi.python.org/packages/source/D/Django/Django-1.5.4.tar.gz
wget -N http://pypi.python.org/packages/source/d/docutils/docutils-0.11.tar.gz
wget -N http://pypi.python.org/packages/source/G/GDAL/GDAL-1.10.0.tar.gz
wget -N http://pypi.python.org/packages/source/h/httplib2/httplib2-0.8.tar.gz
wget -N http://pypi.python.org/packages/source/i/isodate/isodate-0.4.9.tar.gz
wget -N http://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.7.1.tar.gz
wget -N http://pypi.python.org/packages/source/j/joblib/joblib-0.7.1.tar.gz
wget -N http://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.18.tar.gz
wget -N http://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.3.0/matplotlib-1.3.0.tar.gz
wget -N http://pypi.python.org/packages/source/n/nose/nose-1.3.0.tar.gz
wget -N http://pypi.python.org/packages/source/n/numpy/numpy-1.7.1.tar.gz
wget -N http://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.211.tar.gz
wget -N http://pypi.python.org/packages/source/P/Pygments/Pygments-1.6.tar.gz
wget --continue http://pyproj.googlecode.com/files/pyproj-1.9.3.tar.gz
wget -N http://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.1.tar.gz
wget -N http://pypi.python.org/packages/source/p/pyparsing/pyparsing-2.0.1.tar.gz
wget -N http://pypi.python.org/packages/source/p/pytz/pytz-2013.6.tar.bz2
wget -N http://pypi.python.org/packages/source/s/scikit-learn/scikit-learn-0.14.1.tar.gz
wget -N http://pypi.python.org/packages/source/s/scipy/scipy-0.12.0.tar.gz
wget -N http://pypi.python.org/packages/source/s/six/six-1.4.1.tar.gz
wget -N http://pypi.python.org/packages/source/S/Sphinx/Sphinx-1.2b2.tar.gz
wget -N http://pypi.python.org/packages/source/t/tornado/tornado-3.1.1.tar.gz
wget -N http://pypi.python.org/packages/source/x/xlrd/xlrd-0.9.2.tar.gz

# Old version of psutil pip -- the new one does not build correctly on my RHEL
# 6.3 (TOSS 2.0). It fails on import with "_psutil_linux.so: undefined symbol:
# prlimit".
wget --continue http://psutil.googlecode.com/files/psutil-0.6.1.tar.gz

# pips from Lars Wirzenius -- these are at an old version to match what's in
# Ubuntu Raring.
wget -N http://code.liw.fi/debian/pool/main/c/cmdtest/cmdtest_0.3.orig.tar.gz
wget -N http://code.liw.fi/debian/pool/main/p/python-cliapp/python-cliapp_0.27.orig.tar.gz
wget -N http://code.liw.fi/debian/pool/main/p/python-ttystatus/python-ttystatus_0.15.orig.tar.gz

# My hacked version of tweetstream.
wget -N --content-disposition http://bitbucket.org/reidpr/tweetstream-reidpr/get/fa70853cf685.zip

# Other
wget --continue https://mhagiwara.googlecode.com/svn/trunk/nltk/jpbook/tinysegmenter.py
