# Copyright © Los Alamos National Security, LLC, and others.

QUACBASE := $(abspath $(shell dirname $(lastword $(MAKEFILE_LIST)))/..)
export PATH := $(QUACBASE)/bin:$(PATH)

## Files

# Directory containing pagecount files
pagecount_dir := raw

# Pagecounts files -- all 50,000+ of them.
pagecount_files := $(pagecount_dir)/*/*/pagecounts-*.gz

## Phony rules to organize things

.PHONY: all clean h5files

all: h5files

clean:
	rm -Rf h5 h5.mk

dircheck:
	test -d raw -a -d raw/2012 -a -d raw/2012/2012-10


# Rules for generating HDF5 files (generated by Python script below). This
# also builds the h5file target.
ifneq ($(MAKECMDGOALS),clean)
  include h5.mk
endif

h5.mk: $(pagecount_files) $(QUACBASE)/bin/h5.mk-create
	mkdir -p h5
	h5.mk-create $(pagecount_dir) > $@
