#!/bin/bash
# Copyright (c) Los Alamos National Security, LLC, and others.

# Make sure the Twitter test data have been acquired and preprocessed
# correctly.

. ./environment.sh

cd $TWEETDIR

# file sizes
y 'wc -l pre/*.tsv'

# check MD5
# (we don't verify the PDFs because they contain timestamps)
y 'md5sum pre/{*.tsv,metadata}'


# any non-matched keys?
#y "egrep '^[0-9]+$' tweets/*.geo.tsv | wc -l"

# check MD5
#y "md5sum tweets/*.tsv"
