#!/usr/bin/env python

# This script builds GIS layers from TSV geocoded tweets. Given such a TSV file,
# it emits:
#
#   1. a GeoJSON file containing each tweet as a point.
#   2. a GeoTIFF with a heat map with tweet counts in each pixel
#
# Usage:
#
#   $ geoviz-day [--geotiff-width N] foo.geo.tsv
#   $ ls
#   foo.geo.tsv foo.geojson foo.geotiff