#!/usr/bin/env python

# Pretty-print the sequence of JSON objects (separated by newlines) presented
# on stdin, with line numbers. This is a good way to look at the raw tweet
# files.

import json
import sys

import u


line_number = 0
for line in sys.stdin:
   line_number += 1
   try:
      u.utf8_stdout.write("%d " % (line_number))
      json.dump(json.loads(line), u.utf8_stdout,
                indent=2, ensure_ascii=False, sort_keys=True)
      u.utf8_stdout.write("\n")
   except ValueError, x:
      u.utf8_stdout.write("%d *** parse error ***\n" % (line_number))
u.utf8_stdout.write("total lines: %d" % (line_number))
