SpatialLite
  - brew install libspatialite

pysqlite
  - Must install pysqlite from source (pip won't work): http://code.google.com/p/pysqlite/
  - Modify setup.cfg by commenting out the line
    define=SQLITE_OMIT_LOAD_EXTENSION
  - python setup.py build_static (<---Note the static part!)
  - sudo python setup.py install
  - See http://stackoverflow.com/a/1546162
  - EDIT db_glu.py with path to libspatialite  (e.g., if you installed from brew, /usr/local/lib/libspatialite.dylib )


