#!/usr/bin/env python

'''Parse the given metadata pickle file and print, in Twepi TSV format, a
   summary of each day's metadata on stdout. See README for column order.'''

import argparse
import sys

import pickle_glue
import tsv_glue
import u

ap = argparse.ArgumentParser()
ap.add_argument('file', metavar='METADATA_FILE')
args = u.parse_args(ap)

tsv = tsv_glue.Writer(fp=sys.stdout)  # FIXME: will puke if we send Unicode?

for (day, md) in sorted(pickle_glue.File(args.file).data['day_files'].items()):
   tsv.writerow([day,
                 md['count'],
                 md['count_geotag'],
                 md['count_deleted'],
                 md['min_id'],
                 md['max_id']])
