#!/bin/bash

# Print the name of each file that does not contain the copyright notice
# (below); the test then compares this against a list of exceptions (the
# .stdout file).
#
# Copyright (c) 2012-2013 Los Alamos National Security, LLC, and others

. ./environment.sh

cd ..

C='Copyright (\(c\)|©) 2012-2013 Los Alamos National Security, LLC, and others'

for filename in $(git ls-files); do
    if (echo $filename | egrep -qv '(\.stdout$|\.stderr$)'); then
        egrep -iL "$C" $filename || true
    fi
done
