#!/bin/bash

# Test that quacreduce argument parsing works correctly.
#
# Copyright (c) 2012-2013 Los Alamos National Security, LLC, and others.

. ./environment.sh

cd $DATADIR

set +e
exec 1>&2  # send echo to stderr to make output more readable
#set -x     # safe because we have no pipelines in this script


echo '*** Check input files for unique names'
x quacreduce --map cat --reduce cat foo/bar.txt baz/qux.txt
echo $?
x quacreduce --map cat --reduce cat foo/bar.txt baz/bar.txt
echo $?

echo '*** Fail if jobdir exists'
x mkdir jobexists
x quacreduce --notimes --map cat --reduce cat --jobdir jobexists foo/bar.txt
echo $?

echo '*** Check that either --python xor --map and --reduce are specified'

echo '*** these should succeed'
#x quacreduce --python foo job1 input.txt
#echo $?
x quacreduce --map foo --reduce bar --jobdir job2 input.txt
echo $?

echo '*** these should fail'
x quacreduce --notimes input.txt
echo $?
x quacreduce --map bar input.txt
echo $?
x quacreduce --reduce bar input.txt
echo $?
x quacreduce --python foo --map bar input.txt
echo $?
x quacreduce --python foo --reduce bar input.txt
echo $?
x quacreduce --python foo --map bar --reduce baz input.txt
echo $?

# exit with success
exit 0
