#!/bin/bash
# Copyright (c) 2012-2013 Los Alamos National Security, LLC, and others.

set -e

if [ ! -d "$1" ]; then
    echo "'$1' is not a direcory"1>&2
    exit 1
fi

for idfile in *.id; do
    base=$(echo $idfile | sed -e 's/\.id$//')
    join -a 1 $idfile $1/$base.geo.tsv > $base.geo.tsv
    md5sum $base.geo.tsv
done
