#!/bin/bash

# Test some Python stuff that needs a specific external environment.
#
# Copyright (c) Los Alamos National Security, LLC, and others.

. ./environment.sh
exec 2>&1

cd $DATADIR


echo '*** u.glob_maxnumeric()'

x touch a b
python3 -c 'import u; print(u.glob_maxnumeric("."))'
x touch 0
python3 -c 'import u; print(u.glob_maxnumeric("."))'
x touch 00
python3 -c 'import u; print(u.glob_maxnumeric("."))'
x touch 1 9
python3 -c 'import u; print(u.glob_maxnumeric("."))'

