#!/bin/bash

# Preprocess the Wikipedia data and test that it worked. This needs to come
# before the other tests using these data.

# Copyright © Los Alamos National Security, LLC, and others.

. ./environment.sh
cd wp-access

MAKEFILE=$QUACBASE/misc/wp-preprocess.mk

# remove existing H5 files, etc.
x make -f $MAKEFILE clean
x ls

# make makefile
x make -f $MAKEFILE h5.mk
x cat h5.mk

# make
x make -f $MAKEFILE
x ls . h5

# touch a file, make again
x touch raw/2099/2099-01/pagecounts-20990101-010000.gz
x make -f $MAKEFILE
x ls . h5
